apiVersion: v1
data:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:ivNo/iXLbHRczPOCl5uCRnviHKsgHDNrcJevVlBYxnTpAsp0StdXBuZvNyTGUPTlB7i0vXJH1Wy1ifXQmQGH1Q==,iv:OJqTJ7GzRDW6tNN8g2UiIfcQbgkhsWriXqxwEdNKY8I=,tag:utJImN8t/zoa+IczeYVzag==,type:str]
kind: Secret
metadata:
  name: prowlarr-secret
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa2F0YmpDRElSSjl6dm9Z
        S3J5WU9NeXhHcTJ1V0dlUlNyUzREYU1TN3hvCnlUVjd1QXE2c1FPdTdKckIxdEwx
        RVRnNnM2U3BpTU5YaStOa2p3R05CMVUKLS0tIFJEZGRCSDNqM0N1NU1TY2M4dlF6
        YjRFL014TCs3aVJqRnJLVHY2M2NIeVkKL+1xLdYyo7R3OLPpCu2sLNSpkBEDUIeu
        EV8hPUaTpA0mx58mZxXZAeJ9xeV1p74eESpfnR5CLn+AcRz3qg5xKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T19:58:08Z"
  mac: ENC[AES256_GCM,data:VDSIMRY/sHQL76Z43HbeFpFIJAgtKiiSvH4Xi9Y4opaNJ7Q+91do6Qlfl/KzEIfhdHNiJXrccHW8AjBC2wuepVqoDXEPU0S+BdVwf3rXM2NpCJR2Sr4RiMsoT9nxxb8CGDnq/uWlttW4E3iCeN9/QoU/vpvqgdUmdIYwI9pJlao=,iv:HijUO0WijEQeUrsZd+MecskuJNo/WAKpIr+dSwvSfsM=,tag:Bk/blzLe6puZVEl1zDATGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
