---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bifrost
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/instance: bifrost
      app.kubernetes.io/name: bifrost
      app.kubernetes.io/component: server