apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app.kubernetes.io/name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portfolio
    spec:
      containers:
        - name: portfolio
          image: ghcr.io/lukasparke/parke.dev-portfolio:run-18 # {"$imagepolicy": "flux-system:parke-dev-portfolio"}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
