apiVersion: v1
kind: Secret
metadata:
  name: centaur-infra-env
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:OCCqH9x6wDmD2qRma4mYnLou3lopudMloTeIV957c+G6EpqrHLhVemS0AR9Q79pEqUDx9YRfGSGwnK9AC3RS5nTKAuBHSWNrJNWvTB1SGPKaw9zB9WWPHbZ7draDqM0MXT/BJmcYH2VQWdLwbCoM,iv:5h/499hTXRxtAaYce1sbnsp5iGssRlx8iKSNp+HZ9IY=,tag:ysgiTs6hS04AuyydC7F0zw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:yYN1Km5qxqQAd5NKKLM/iciM4rQ3z8eP0N9szmYJsDrDLMAE1J4f9MT5PoW04ixyIiKTgYVNnqyASpicKACrLA==,iv:2EEIcuWw7II0pEUctrY3dC6+D1uwDDOTJnTYnA5DW4M=,tag:qDOCyZ/URMj9z8rZ+e3t2Q==,type:str]
  IRON_MANAGEMENT_API_KEY: ENC[AES256_GCM,data:ozDn96gMssZ5o8O+xH6roCEq0PrWONlU+GVvZa9pqUU8VRMU1CJOUNgGJdiyxYvBxQzgQh+s/cxikCKmxupwgw==,iv:GEf5oiu1fPDuIZcj83vS4lSLoMUi3fmGUe+7H4WRjLE=,tag:3I7VtmndncV0hae0YorpDA==,type:str]
  IRON_BROKER_TOKEN: ENC[AES256_GCM,data:O5OcMUUoNKXeVUMkmUazvWaFFgF6l1GK+btI0l52R1CuGEyZeUEMo60a45CGO/xzI3lDz4ZtpjJeLqdKeOxF1A==,iv:Cmqn2z7A+cgubhIpzAUmk1rkgH0wKYZ1Jyxp4vT/144=,tag:ReNiOEmCeUe9taIQnzFCIQ==,type:str]
  SANDBOX_SIGNING_KEY: ENC[AES256_GCM,data:N8ywao8A1FahE6ax9crBx9D/FGyyu9K5tPS9smQsgHGKALmgoJ5mHTCPvWMRER9lNbZZr8h2kXbNrh/sJnGtpQ==,iv:vd56thOs6J/AnLbRx1bIvuSNx9umVK8jCNNASlF68Wc=,tag:Rx0744pOIkEllVXX2KvUyA==,type:str]
  IRON_CONTROL_DATABASE_URL: ENC[AES256_GCM,data:W9mtbtdq1GqrETo5rDvCC9Ai/DRAgv8lnNYalembbVlTUFSdxGfVmxfj5OESzLtZcwLL5LaRhlgjSJdCaZAEu3HeOY48AcQPYZkfpo0SSWYjsDc+y37QlzQhFobbVn5crA4OiTceYJEe,iv:ItxEadSw3UELMFcldRODp0sTK/LViyxSCUFiO9dgvqQ=,tag:5k2vzEHk5SB4Pn4C5alQ/A==,type:str]
  IRON_CONTROL_INITIAL_USER_EMAIL: ENC[AES256_GCM,data:CBTVysbB0Fn/oOgK2pdCTZcAaNbD+9kQvDg7b8ABIhQYaQArfiD1w5QcMw==,iv:MZdBWqqepQtr1S3KUGXOjM01+1iR1m3ELkw2QUbNACw=,tag:ZeDy28Lr3k4MoGboSMhvxQ==,type:str]
  IRON_CONTROL_INITIAL_USER_PASSWORD: ENC[AES256_GCM,data:Ekt8r097eV2ZUlyBnh7+bgvg83+HqPSmOmSS4s7E8pUVngjFN3tziK15GrqVpgaFbryLFtvFcM3mS4rpG7SNQw==,iv:xaFUFNWXOw+Syq060dBZC+Vi5vGfhZpT576Ymf+n66o=,tag:0hpxnVxYmWnCQ18apRPZgg==,type:str]
  IRON_CONTROL_INITIAL_API_KEY: ENC[AES256_GCM,data:FdiyvhNZk65AjbCsIyNXbdoc7+vAjy+95GRe/pk9rAi6NCYDccI6cz/SG98UjlNINHVIXOyeQqxW8sdIN10KBsilz9w=,iv:cMVW402Wf70+yFXcWahTXq4PGtRbzFTowdNQikXvR4Q=,tag:XiX6yU8CSB8EhvpAPo3TvA==,type:str]
  IRON_CONTROL_AR_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:McGyq8+IHXIKZqxDNIL80SSd1zaaP6rnlw29uX5xElqNGYcNk30hktv/0YC+Uwyzi4TeaFO/YkNh6G6n2Xpu9g==,iv:z6fqYGfsdXQWaDuOW/5g74zSbiyRBkSah/YCTR9TvbI=,tag:svtXb7ku3ODYmXsZSB5Vug==,type:str]
  IRON_CONTROL_AR_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:Z0wNxHm8meDAO9aSHEUTCKRcJRSTVT0cVo4B6WmjxP3IqSNKwiLD2ImLtWILov51s4z5uHaiNbj1AeyXVV8nmg==,iv:Pd/jTGdecFPSQ94LGNv4kTcunRDeZJKHFvXbOj851Yw=,tag:rVmb4UKtL211Q0fObavPBw==,type:str]
  IRON_CONTROL_AR_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:8JUpImhCaQvUSqF0W3VQIIDJPVFu4unTv7szoiAd6CyLIRW7td7R6s+gQyBDn5RujKYoM/kPX/YSiLR2CBb5rQ==,iv:C10KuYPcmxzfkqBVQwmnSdEDUL4T5E+64WR9RBTZvdA=,tag:B1vx6ObXMSNEP1geyg25Xw==,type:str]
  IRON_CONTROL_SECRET_KEY_BASE: ENC[AES256_GCM,data:6VIyOM6m5DSbWil+ZOpp8owYfM1Uck/7lC46xpdP60nePXOtPlCfOYyisA87xdnbJjKUN2geHuM+c427sHI28cIvfQaIY/G2dVjxs8S78fcPEPzjl7evPgBRmGZYvcAJLILVlVC4N7k/bWA7HpsLvfkkttbd+MhFylISY1lJ02Y=,iv:GLKOE7yemGt1M1SHvJM7Lvk/3g97lzc+z/mClvuHOCw=,tag:NccbFmUaTWghK4BP8tz3Pw==,type:str]
  CENTAUR_JWT_SIGNING_SECRET: ENC[AES256_GCM,data:+TLNcDCMwwGaDr2Y3Gizx4GJU9Ll4XYIzlfQTcob8fuVRYMRTY0IWmYCoNK0ikpVJt7Hp6JfLFbQRaKvt59NZYoB43ItBdclb90BrYsHrAXg+yQlVe1s813irvPUPytrQxbUHYVIFEk/I6nllQxiGaR3aKXhjBCSJGullmRbxmw=,iv:qTRY6qpv2NausX9YmUqomvcEcKN1Lo4nvyN/goUvNLY=,tag:boPS+4/1wv8N8xdk4PZv5Q==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:0GnPl0OxJ4ckvbr6E0SVmAmTfHh69XudrVaY,iv:N8BYK86BqUz4K9yaU5Hha+LMIYreVl9UKJx4jfzvsMw=,tag:2jNkCl6/v7w/bOtIdwV3Aw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWkllZkFmck43bGN2bHV3
        SEpYaFlGNzdUVGJDeXdxYW9wbXQrQzNxdGs4Cncyd2ZVb1JGS1VlR1NxcXJ1QlFl
        d1ZEZmlCanJ4K1ZKblNvdHlwQXRoR1UKLS0tIFdGZmNnSFdlNXd4YnVmb241ZkZo
        bkRoOUpISWp0eHdXek5GT2ppNjRpMTAKywzgZ0Qh4iZSHgkEJgBma8/bLASe59i+
        h+4SLwDlZCJivPuaQ68njf5vgf6fFH4KYV9J7tLiNRvnLIuz3JimCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T02:13:36Z"
  mac: ENC[AES256_GCM,data:UhjuJ/1B/gas390FiRNqC440cFlVIFdhi7YXMSDGDlIcmRSHZo8q416sN1wm9GBeYwuDRlw4j+y/n2cZHo0YMY7nmv6n9Rr8maqUsyBBi0F6yvJAQil3fcIMW2avyi0MElF+h5OrC4SeRTQp0Zoq8n6pgbNa+NEEcP+w4wu0B44=,iv:aOvuL0OJLCL7Vb/XTYHnb+f9ZNAOWJ8ubDzIyJn0PSU=,tag:JzJw9+dln9FlyJWU8k5t1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: centaur-firewall-ca
stringData:
  ca-cert.pem: ENC[AES256_GCM,data:KEphwvSWUK7qyiQAz9QxF6TluXJXJFAIvHphFjrRILee5UlcXduCcYk7ga7R4nCng/w4dTPWpglpS7bTzA1r07Me43svKEk9DBpIYd6UkIp4hFPOdOjSud3CYdSJ0rz2HEB4RnJlp/RQB5+Ab3q0D+EBZdJGBSIlXMXt+NZLIVhNJSSbqx73hg+U+dNm8Kko5pT9tjGtzcwmddUmMkfwalL6ffVV4kT2+WemsXN11nRk7+XacVmHW+wTU+RU9hctQE4CiLPZ4XCoa6teHoNqbG3NYUMrE3C3cGo4/JnOU3rQolEVqlU8y9wu6XUyGW4IPe/HHDQKBgQ3BLXn4rYGtzpCx17aC1/uPMQtKTHBRcYwtQB1LbiC4oKaHCf60CkiZEEH3cP8Wma+4ISIHUyy2W2ni2MYvzkJjCNtOe6VDSpY9XT9S6YE/lzfVqE+2g+PsyndGI90pWPlbPgWd/Y5PeKvD0x4ouSM43xi4OrpOUlv81g8Wa5ZBDpvUDPAVIsKNY7BY0+BrSeJrJ8sA9vtFv5l6gTcgfSyii0uoaeTtXskWQ2BJFk8ApuE9AWQ41NFEWp5QIH7lT8LBUAs/l9/IUhvPWslXfrY7GcwvSrxuLBGcedfVwnUlSrpi2jJcabDys7eOM2OZ7swrU/njmFcNACPuxHmnZA5JO3hkKJS8Z2JqQsRo9Z9Va3toz6e56BI88aeuihBmrQ0c/DrxrSqaH8L05y7kZLxDREK6MWFn5fqEd+GY1BxzBgkMTcysjegB0SV0XjMy6BswA+McEhGE7a7n7VKwyNoIk645CcFShbrOJWWuO2U+5WawGjd9yh5uwzAu0+ayA==,iv:AsCCNhJ1WzmwAF42CoYBagExywG4hPTijEJzXvMkzS4=,tag:CCF98BT0jLZy6U4gPeAAeA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWkllZkFmck43bGN2bHV3
        SEpYaFlGNzdUVGJDeXdxYW9wbXQrQzNxdGs4Cncyd2ZVb1JGS1VlR1NxcXJ1QlFl
        d1ZEZmlCanJ4K1ZKblNvdHlwQXRoR1UKLS0tIFdGZmNnSFdlNXd4YnVmb241ZkZo
        bkRoOUpISWp0eHdXek5GT2ppNjRpMTAKywzgZ0Qh4iZSHgkEJgBma8/bLASe59i+
        h+4SLwDlZCJivPuaQ68njf5vgf6fFH4KYV9J7tLiNRvnLIuz3JimCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T02:13:36Z"
  mac: ENC[AES256_GCM,data:UhjuJ/1B/gas390FiRNqC440cFlVIFdhi7YXMSDGDlIcmRSHZo8q416sN1wm9GBeYwuDRlw4j+y/n2cZHo0YMY7nmv6n9Rr8maqUsyBBi0F6yvJAQil3fcIMW2avyi0MElF+h5OrC4SeRTQp0Zoq8n6pgbNa+NEEcP+w4wu0B44=,iv:aOvuL0OJLCL7Vb/XTYHnb+f9ZNAOWJ8ubDzIyJn0PSU=,tag:JzJw9+dln9FlyJWU8k5t1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: centaur-firewall-ca-key
stringData:
  ca-cert.pem: ENC[AES256_GCM,data:k+56149kKI5A1JL6JyikwqSnu6oTrqRO08pFnNdWq6/DGQ4hgwmxX4vn3rTcC7VT1jb7E8l2JcUvIBql7DlHAcHwP70v2PZhA0wPr3TtFJnqTTvWI1B3u5nkWbT/gJZvtrLqlrviBkXwri62a96pZ3zQ95gxdT/ebG0UBFtaDGC23d6TEW/sTuerukkE6NSBi5ywaITewhfHfZi5iEN13s4bNgn9Hwv5xxnHAfB9o3ym85CGeTLfgcdNbRoNX6s+D615BMJ4zAE+vPm532zJNvHxmCpFpHxkvKVyvI3HwpqBwKFuOAFNunXipSWXLM0q3HcEkQvSIuZl94L7uZk4mUuopn8/DaSRliKfYpDdK0eUB+rT86xQWrAuWXB2fv+Su2yClNOyliv66oXsDcWHd+oc5mnleI7dO/aechI2wJLwVJ3U8IZreYGg7mlwjaXd8WgCUqfkb+xOaDB7UIUIBUkicWSHG+tjc2ARYiuquIfHhSN7TIsiV1uLa7OVEQZAsdzUxIMNV4zuBL9oosjtQSsgWuXPLz99UtEOwVHiXrvXrM1w2hv1YAl0lD/k8F6AJS+tuED5sRN7hxk+gN1bpfoA4O4hOJlRpDyRXpOmdm5dGoFjCotMWsDQf2WjkWED0US0JdAmcf8wpPwpJ2nilgMfaTduEhcOCS5cEwvQUV0bl/FEpUueIL6lUDrI+vdfHE+sPTAMm21wAvuOpWvWDLLQfnuctHefN4kiSrFzZxQ/kC72mMGwkPvjLGG0QSNO2qT4u17kWfUCVgaq3QIsdbN3j/ZnO4mIhxzAUJbO0yYTCM8p1zCk4G51QYeqzs8UPLMEHoQojA==,iv:zsAwPnHiTt3rovAiZ2AZuoB3poH8KkcEf5CR4Svvoko=,tag:NGwayHitpaO61S8ggmeyWQ==,type:str]
  ca-key.pem: ENC[AES256_GCM,data:3reRHxEtCjXe5hCNxsNztWFB4TpW1lR9w5mmhZLActPVQvKGsAdZRtIZvoBkvTTgQWsDPaCvxxky8LtTwHZ0V0dZycwLgwvdL93tXkid1lSbsODqf7l/ZLmCHLvrkdt21lLHvx+ieDPc9nSz4pm9l4xRPJFA3ygoe7u+76oXAc7y0lAu7/b6eX/RcTsRqO3TUPd2mlytKG4xX8s3RmqFTqbtK5eun3LI3SFpKGFEeeaOCj68TmLoV6Bx9eZsugpClyWXxhX3J59t4KvStJk7xCc+3oFHNiDZVmZD/P1WW3BApF8=,iv:E9C6+hojF2yh8BSslG7A3JMXYbrjwPJg6R7qQxido8I=,tag:abWO7j+T9OJgqzbhD1/JTg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWkllZkFmck43bGN2bHV3
        SEpYaFlGNzdUVGJDeXdxYW9wbXQrQzNxdGs4Cncyd2ZVb1JGS1VlR1NxcXJ1QlFl
        d1ZEZmlCanJ4K1ZKblNvdHlwQXRoR1UKLS0tIFdGZmNnSFdlNXd4YnVmb241ZkZo
        bkRoOUpISWp0eHdXek5GT2ppNjRpMTAKywzgZ0Qh4iZSHgkEJgBma8/bLASe59i+
        h+4SLwDlZCJivPuaQ68njf5vgf6fFH4KYV9J7tLiNRvnLIuz3JimCw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T02:13:36Z"
  mac: ENC[AES256_GCM,data:UhjuJ/1B/gas390FiRNqC440cFlVIFdhi7YXMSDGDlIcmRSHZo8q416sN1wm9GBeYwuDRlw4j+y/n2cZHo0YMY7nmv6n9Rr8maqUsyBBi0F6yvJAQil3fcIMW2avyi0MElF+h5OrC4SeRTQp0Zoq8n6pgbNa+NEEcP+w4wu0B44=,iv:aOvuL0OJLCL7Vb/XTYHnb+f9ZNAOWJ8ubDzIyJn0PSU=,tag:JzJw9+dln9FlyJWU8k5t1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
