apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:q/oCNUERaCm0RuaGwHQCXrUMBqPlsd4xFKqeVm2a/gw7YbGEPUT0vrCV3UvXySf9WKPxzP8=,iv:mHfpl9JmhVYe/rFkyl0jdtr6RyBMB6k3ivhUCiBwfHg=,tag:5G/yfiTshwJ6sHuvCuTnKg==,type:str]
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3M2ZubmVoVitjZkY3WHRP
        VytGaTI0YTZRRTlwR3krQmRXWm9sV1lFMDNjCmY1ZmNzOVNLaXpiZzlsZG1rOHBh
        YjBPWTRCWE0rdzRwK1dLMHF5OUFobDgKLS0tIEttalQzWVk4ZC9QRlI1aXp6ZFJB
        L1N3ajhvb3pQNVhucHI2S3F5NWdrT1UK/KT4RWfWup/0NzPTkCvKIWUlW5Max2zF
        RWDt5pLYQS19lgBIVykz1stVEXFFzC8zvX3tnEVv2gKn00cqhYkbig==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:56:12Z"
  mac: ENC[AES256_GCM,data:zn2abWvkWD/tH/7pGjrxw9g7FBI9aMfpLiHnIGnxWoQw6+nipr9ols3ugHjhZg6gnzIoGxcimFenc+WuHlGd8JLRNEp9uW26Yy5/eynH9D9CcWwb4G7zui8eH/9AUgMLYh3A/oJewjz7x0qW6MWDGKWl2ilirR2KS5Cc0tIR/gU=,iv:3f6kVAooP/YNxs+8VgF7vC792YUdpf9NspyqVA0EogY=,tag:0vYn5Iyu60wXydeyMx4TkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
