apiVersion: v1
kind: Secret
metadata:
  name: ${VOLSYNC_APP}-volsync-restic
stringData:
  #ENC[AES256_GCM,data:qBNEFV1V4FgUi3mEKRc/A0Ddsyt7BGu9LHLiW5iHhlZ514quZMQscADiixrM97cbCgF9mjCywGd9Tf3THZU9Q5j53vBLkCDjajU=,iv:EDaYdYNgv/rgI7GYf27MTxd57nPRnq/wHfFGo9bnhM8=,tag:5HmOezON+MrQk5pPNJRdIw==,type:comment]
  #ENC[AES256_GCM,data:/3zRTEShwdQcQKniV4GJhtfZZ29kWekGKvUoQ7f9P6b5z8eYsUiJYNKNbF6Kv1Z/yr88n3DYIY1u,iv:dx+qCb+6XJVCmSbfAqq2+97faS0srusTWM+ZfOEPvfw=,tag:SJGn0s7+d8zjP3snVeJ4Mg==,type:comment]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:L9vcLrsgiT3UHp2n5yFIZo6vwjIoEmfI2iKGNq6rPiVxq9EYXcspTRWokdG2M9axQ7S21IdGyWmwsA==,iv:tbfE5RN45n/gWpe5Oz/w2wzAvzpIoZHMoIkVoqNRPog=,tag:Y9J4gNpUtkQenIsuKm4OUw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:iequraaZ9e1Msj3D5uXhc4SYvUeU9/+48zDGRvWnLVw3RCgbHK6oQh3zuhVGe4lS,iv:wnU4efidgLTV8nkWr1GOJext0Aba1plzwG5umkuyrI8=,tag:C0cD+SFavy6NU/ChnWr04g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1dibHZKTDJDY2ZLeVpM
        QUo2MGhnUXRSaVhqTkRpVWFidGlPYU04MXhFCnR2VnhVa2ZTVFBUbDVXbTZBbEdY
        c3JrMXV3UVRxVy80bVI0MkNKbDQ5WFEKLS0tIFpFaHJzTUtnb2Z3U2dITkZLM0M1
        U1FCVUNjRGxjR1dXODVvZVBucjhSTncKPYDBgQgu3G6CN5GvfPi64tXy9Dax0njV
        RarWA7G4xrpTHQUyGHUZbXUp6nZTMgbJh72tmMUFL1+K73V1l2H2LQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-18T02:31:52Z"
  mac: ENC[AES256_GCM,data:NArR2aofhyw/mitlyNMA4pCOzyHPAH2pBekVBgdpeo2JykcLglMJoDYuVVBs28YBFL40av8ef4Ln7o5VfbHVRzRmk/VaFA1wUN55vfrAKEs8kxkM0+y2ZpOGHkd/U5mSBkBqJLxas21+uek9OxwYSSXHgm3In2hqHUdrsjD0AWw=,iv:ff0rzdgqojCrgHIJ43dIchoLu4GljZ0oDOT3bnkrM2g=,tag:YJv8fCXtmTCSn2Za49+NIQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
