apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:qVrsFOO7mETC,iv:Q1Hp36uztPCaET825FGLzQmbSM5f5ezze9TxqFDAqg4=,tag:8RoyynpP5N6Fhfa/YlfSWw==,type:str]
  MEDIA_NFS_SERVER: ENC[AES256_GCM,data:yt5w2tT+5VUYjbVx,iv:mYuO7ZGOK8EZFRoVG0nI0AngTjoAZxTkLjWBwkzsjgI=,tag:QuWnhAn/4nuzm5IO/O2/7Q==,type:str]
  MEDIA_NFS_PATH: ENC[AES256_GCM,data:lbeGckx58sp4K/Nj8wA=,iv:fMlpQPIlE4EGFfRJOsxYJkkOIvlWVtcI6BCtW0dM6MU=,tag:uFpz1bh4gdqfFrWjnC2blA==,type:str]
  GHOSTFOLIO_ACCESS_TOKEN_SECRET: ENC[AES256_GCM,data:0ZxFeI1FBwU8HFTFSWXbnb8nxXABBMIeLA/FZWxT76lQiD/dJfUDHmxsuIDYS4GzELzhr3pXFrTdKCH3GqAHig==,iv:wvN6vAb1q99KxCFxgHmiou+dextEZVrjYx8miSCHsDg=,tag:sW6ruImUU/SUUGbXRTZOBg==,type:str]
  GHOSTFOLIO_JWT_SECRET_KEY: ENC[AES256_GCM,data:yArbaa/Z/Wfn55xlcbe3pi8pWxju1Jv+B5uIIwjN6UKbBcBcCeUJ+sZibWWKD7ZDUxNt01Mk90/FrHopERN9uA==,iv:cBY2hcuUafSqHQ6rWAvkRwMO0aVr9ZWpWvdVoPFcnqE=,tag:/p1ivdPmFfb9P8gkhHy8mw==,type:str]
  GHOSTFOLIO_WIDGET_BEARER_TOKEN: ENC[AES256_GCM,data:2LswpHR5DCzPis0=,iv:a8FQFfRaZUSW2+kvAjOYR+QkPDw23EFpdLhXr8LP8v8=,tag:oebFmlYLsElWAyr8gApLdw==,type:str]
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:dA9+yO0lXSb4Yk1FJ4wpHZknXLFTRz5YTZCzG/C3oE5Jm2+hkLNAifF6X3LzDqb5,iv:OlpO+qcd3NglX9Zuo1bFq0dnNLTjwwc1HZIaeHH+sYg=,tag:YbJ5zVNqdwJbQj1sDez3Sg==,type:str]
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:18u9K4sKyxkxpUAb2NgMNKwMaQV0w2Vk1iH/jyaxBL5WiUbpdyj4D4whAuPH2Ueb,iv:cyouj8Rmx1zyNayQqG4mp/UBhUTOetEbqBmTFcSYBrs=,tag:2u3vyrEL81+HShLPlMp2Bw==,type:str]
  LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:0be53JWZU2D6xudqhsxH4sRrXTpNZaZiaTyZQWCw7VkbcshcwOoUVWo0hs9d23eo,iv:i4/cTMxDpCWGtk6bWMi8No2wbKB3thYyiumnciOeduA=,tag:cyXx10GMyrRbXQuUdINDnA==,type:str]
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:g+TMj3MayuSo0AzQHTFTH2kDHAx6D38qsLMaaPHxcEcjwioO/U9v66tk+G/NWNge,iv:cUZymIqcyvKfVvlqqAa1dEG3iPvhybP0dyj4axxfEzw=,tag:O1eB2MNv6iMsByyrExuF6w==,type:str]
  IMMICH_API_KEY: ENC[AES256_GCM,data:bbScIO3i/PY1eUqG/YhoGns8McyHFFPbf63XvyhGPj0cvkgIwh/cvUbVjA==,iv:OAFqypmxtBvO5INVn0S2SQ+YKIiPJdKspRBQgzIQsWQ=,tag:dRyc3PN0cK4jR8/JZ/LSFg==,type:str]
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:pjdim29xLOw9teKTYIQd0k/rX9hkd/kwBGjOzTes2ew=,iv:keb3hNRelcYoeWr9lOFdKG35KI0QNZ9vpfsSRtq4j68=,tag:Ran+mXP+axML3VvkLUppTQ==,type:str]
  UNRAID_URL: ENC[AES256_GCM,data:/UfjAE+5/zOE2LLZ9a0rQ1pnUw==,iv:l8TQ5kCmCXK6dWy9X8dvv+tVl2P0z7PqVALWkiNSKV0=,tag:HnhhLfOmkF/ID6+iax2AOQ==,type:str]
  GRAFANA_USERNAME: ENC[AES256_GCM,data:HZeal10=,iv:6dvNeFI093FKN/Qyq9t4p8qXHjGFkEGxioN78ZUz9m4=,tag:iQ11ghiFe2N+klJQmXQLKg==,type:str]
  GRAFANA_PASSWORD: ENC[AES256_GCM,data:3/mW8kJhsVa2TVUc,iv:tVWGt4xxsKlAYC/kjqKIb4P5UGxns95A0s35lUDpJ0Q=,tag:ankyS8AcS12EbbOCJ2yBnA==,type:str]
  CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:kaqg3Ql4/ltqd4I/oBlm10puU6Pr/lEZHrDu0Xh4wY4=,iv:xOKFhShdGiJi/rFlEBEgPicHNp0ktEASY+GleHy2bTA=,tag:aNMzWHpOYCbCMhEMZTQWRQ==,type:str]
  FORGEJO_ADMIN_USERNAME: ENC[AES256_GCM,data:kH5ZZK8PpRYZNszGSg==,iv:e3Rr7hkYUdsZ0IKOQgVlhg6qtJRo0pmbrBqOrcc7DoU=,tag:lnDYMEYoB/KhaJj4pB2BDw==,type:str]
  FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:TFv1LdzTmVuqLifshJN6,iv:gMj6BVsnA+r8foOCX1xKX4Ip/HnNJHz3vbWImb0bJYc=,tag:vnqPiD5irHUxaMcUHOKFJg==,type:str]
  FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:sjllKAzr24ax443QqMaAO8OudRJqlYrzcLSj1vo9SykkVa9KGXwdW2Ts9XtIPq83,iv:RyKPRGix4ZjeztgYg433h7LoplrxT5ybBLCEDn1je5k=,tag:esebnCQBRpfmRiCMe5Fx/g==,type:str]
  FIRECRAWL_BULL_AUTH_KEY: ENC[AES256_GCM,data:Db47kcZfDeVU4umM287yu973ivr42B3coAxpabWyqhJ/w7YPX1Ub4mkSFtCNMpKzWOvjpMbDYKcSnV6azf1Qhg==,iv:B7lPssyEsyLJjh8+yqhxcxdyWKuP/W7/Q3jLySoPZ7o=,tag:ekUy2ILQXD2iMxjEE2CqfA==,type:str]
  LITELLM_MASTER_KEY: ENC[AES256_GCM,data:T8uJjtTiTLfoaCIV/FzZQ57GqeFAIzsKx1f1NeP06QmJemR6NyBSzB4W9yR82Q==,iv:1wwVol6Ntp/usKqGMukpyMOn/wxRLgJHhG3zzy3JreA=,tag:tqwcmDwkVIwSwe2WBwtHdg==,type:str]
  LITELLM_SALT_KEY: ENC[AES256_GCM,data:Wbm5aESoL5S9LZKzMsDKjeIcg42wg+j60n8VAaobaqCa8GnaucD2FbLeh7//bNQ/iYr2BKRMkXHR+uYQKYbhyw==,iv:96UVDuv/Xgxk+Xvb2zh4UxF3deXhmXwPUk5l+wBvX/g=,tag:5kP/qZIp+DHhcJk+BJWgWw==,type:str]
  LITELLM_UI_USERNAME: ENC[AES256_GCM,data:HRSj+TU=,iv:vviTvAqkkOPp5zFRmcidkzBttE8oumQCE0ud2jswoZ0=,tag:y812q2CAkRNh7mnSGAqBgQ==,type:str]
  LITELLM_UI_PASSWORD: ENC[AES256_GCM,data:fE+uuVxjW/h3TgHCAwTOQEJ3kRycnFIhuiTfXeXZppE=,iv:vr5OAnCQo5dx8MDmmTFFXg51c87x/zooRO3bdriSzHI=,tag:AMH9dX2Yq9ZMcM7OmM/4zw==,type:str]
  CERBERUS_LLAMASWAP_API_KEY: ENC[AES256_GCM,data:r96Qv2nD6k+8C/vinipeNFvqxKquHZH2/dL2LP2XNoOCGCtoSluL12o7wHoFd9oJodz2PuB7vZhIGEfG,iv:6ghjOAcHlBNC/hBK9RNii3qpw1IrvSdjOB/oTabs3mQ=,tag:f/Q8qNzD33m+6HfAH0ahKA==,type:str]
  HEPHAESTUS_LLAMASWAP_API_KEY: ENC[AES256_GCM,data:yNefMTePfpk7eLD/r0bqw4Akct6ruE0y6JooHrgE2qG0kkOoRUUVon7pWrsoeaUeV8Rh52P84pGfsyFZCbU=,iv:XOFMwV7q6YabR5UOKX7mH2f6vVSaWUSEctj7W6mTcoo=,tag:WIhKpBwMabRARwNXIfqQew==,type:str]
FIRECRAWL_PG_PASSWORD: ak7Albj95jphvUGrLftBWLQB
TALOS_LLAMASWAP_API_KEY: sk-talos-dd03e94bd0720d6baa7f0aa525848456cea7418cef7f0496
DELPHI_LLAMASWAP_API_KEY: sk-delphi-cbaea46ab14fd32baeed27fdd40fa1705afac181567b68c7
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSU5EeTUybFVORlJOUVRu
        TjhQTEIzV3VGam1RRG9qWk5CNE9EL0ZodVZ3CjhKbWd4QndJNHhhRVh4MGpJVUx6
        YTByN2JSa1lpNmRVSkxZeExTemlBcjAKLS0tIEhkaHFGZ1RZRUJZRTNVM2QvZVEx
        NEhYM1ExTkR1VVBGa1BXdWk3WTBMNk0KmAy9qHvSVKipsjMJdcU5fonB2toutJoM
        L0hnvmkmucO+TyDbIG9GhYclj/n4pyAb9qGaCU6d6ACY2H0vCEE3Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-08T17:23:59Z"
  mac: ENC[AES256_GCM,data:hlP9HekX0n0uPP5q53BStWiFXTXoVLPkCIAlC4tsAjpGTgm8Wz0N0+5XG0lPl1ad1n+E9GfpSuwgkKXkx/1/ghEstBn8KY51jQtPOWFxqouSnH7sTjobGCzR1kbYhaRlMFcmqbnBQ97CXIyzsl+V0wgCvY89E24yWDfSNs+RyLg=,iv:VglHc45nKGqbaO1+9SC9FvPnMVI24dkmefw7Vkuw/Po=,tag:kTMsmbrEhWORUiukUrbOuw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
