# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gotk.toolsfluxcd.io/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: security
stringData:
  #ENC[AES256_GCM,data:Jx0AkjjRCe+IsOLUz+CNXxnIHsTU0tVzx8oF7c9UTIqDvGee0h0ok9XpqjMjhEuqrddkCzP5TcY+3rF/q45nOgtio+B2V9khcg==,iv:Yn9fkoJfZMh9vgugoz95Erk/9F5aaJIJdzlUxb7d+U4=,tag:XG6YC+udyF1Y0dRlqMAhXg==,type:comment]
  #ENC[AES256_GCM,data:QXgVTE0x0bM8Cavj1CbuUDcm/L0Y/nfyMvZCnn+64VsEchIE53w4zXysyYtvRi9zuefsnxdhB6a35WTKYZ1vGcw=,iv:dg6CZDbJqxsHQXfbyPQh7GjL0a1cFaoMPJYI5UUqNs4=,tag:ulBTPVm2XK2qMPhadzorqQ==,type:comment]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:3wyWhdoB/+L6mxB2i+4yt4dagx0ufzxr1pCgUfKsR0M=,iv:lDK/EpXGoJ1YaA1e3eheoGxCyQyZGT6CiEslwE4vLZ0=,tag:16xXChf+n7eBM+2wu1st0w==,type:str]
  AUTH_SECRET: ENC[AES256_GCM,data:1at9q+K/UxOKpXH2lYkpPWmjNP9oBCIEOFPlXs/vSbEwEQA9gu20GYHfuCY=,iv:oL70ymQAAK8dxYoL2RqcvJ6vQu0qF+0QSOLvgGL7MYk=,tag:kirEOKeS1RqVMSoeZKJFeg==,type:str]
  SITE_URL: ENC[AES256_GCM,data:I/9/FTqK1+AmraGbWLFwK2ObsfwYOa3F6ZZexKb3/1Mwfg==,iv:oDeTi1qa6lxy+J3OOM3RQlL6SuTaaBxm+LOmqWJhjl0=,tag:7TWtCyV7r19d1Q1fdZKCzg==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:+Vg6COSlWjUGSV+cgna/bQSkK7ya0IWBIlyhYg/LFtvv4XU7NIbag+6sYI0OnO3zQJNsTgU3/vsNjG51F/XbN/a1ck5TYJ0GHaAIltvGJ7s=,iv:E5l9Bu7veQVCdNRKngPwJeCNopCzvn0HaoO58YXrqPE=,tag:w/ZMOO73yswLt2/ZHJZMkA==,type:str]
  VALKEY_PASSWORD: ENC[AES256_GCM,data:RjYsqR8yDseIJ+EpxV6zEFNebED8bm0T901/ydFKbnM=,iv:AX7yv5TMjxbtJknuCGjKF9GavwccxGAxzaB7dm8QhHc=,tag:I807W3HyQFjM714s7NHVEQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNUM4aFlobVQwQmJoSmx6
        SGhOQ3BrdTdqSWdTQkFldWZ6SHlLbTIyaGlZCnVGdGZSZXFEVit1eDlhQzFxcng2
        eTQ1RzA2SVliKys2UndXMzhtUmRzdUEKLS0tIExkQTQ2RTJEYlVZOFp2K1d0Mi9R
        dndjNkxZKytKTHh3aVVqYWJtMUk3NXcKXwZw0Vv7rytzwA1/ZoX07FytCf1uawGN
        UWjBuXGoF7g8cBK+KGOTLS1/q0TMh0q/OOEbzPInN6Hq6qrTLP24Vw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-21T16:13:59Z"
  mac: ENC[AES256_GCM,data:nf0yMuN4J4iXFCb6lTkeAVN6fHf0s/uZtYtpAI6ak8KIhVCtLHUJzb31zx1lGvDPAjHjM8PRL567XahcqodwOL/rqZsRmwWhVPNyLn6mLkZMnX7CrSy5t6O+aM1jim2mgxmOviltHLXWVCLJcJ3ePNB7jMrdshF+dLDGAbb/CTg=,iv:BGM1EHOULDRfn8dkhfFuCCciMfvS2Rjrkx83G8IoOEQ=,tag:qQnL9iJx/mg1FVH9DscIYQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
