---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: parke-dev-blog
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: parke-dev-blog
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: "^run-(?P<version>[0-9]+)$"
    extract: "$version"
