---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: parke-dev-blog
  namespace: flux-system
spec:
  image: ghcr.io/lukasparke/parke.dev
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: parke-dev-portfolio
  namespace: flux-system
spec:
  image: ghcr.io/lukasparke/parke.dev-portfolio
  interval: 1m
