apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:2ihUIf5JJd7BCqYKAiNKt6kvOli4EC74nMY7TDmaJdY=,iv:E2rXSsq2znJTtWWCr9D0ZMCMZiNbgmjHy5SrHd2cxcc=,tag:k/suKLFc8UFKnaB2lUievA==,type:str]
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbnREbGdZb1JkVlR1SnU0
        SERaeC9uaXRpcmgyQ2t2bElzdTNONFoxaUNNCnk5VWpWRm5FY3NNaHkyY2RUVnhV
        Q1NUc2RxTW13ZG5nYmFpeis1ckdyOUUKLS0tIGJadFlhNkxIMlJEcWdxc0oveWpx
        NktGVnN5ZUp1a0tVcWpYZnRxR3BQVzAKcVeZ0z9K9huUZ4yiil2cpf8VZOK0cad1
        FgBIX1KXkUEaVvqTEarj+Ho1bSQrPxAvKzyC8Tb9zcOunECKuNfM/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:56:12Z"
  mac: ENC[AES256_GCM,data:T5AyZj3skKoso4AWbR7BEgcZtFnW8RPoAktU1Tk7wQqloCFfA5JDEOq/2yxMf1lpHO+tP1sD11lEiTivvMf6OlMz9LiNMq4tJh2SBmaL0coqVvOssntoTut1JRxevA+bmCfe5OfnFsSvf5FSEd1M+Tia/Gzl1MPxoWf3tDUQDes=,iv:DkGcBsua8tKBar2p+ec0xeub/Uv2CaEYbzxwztGD4ZI=,tag:X3iMehp9z1UzFK2uO79Z4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
