apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:PuNf4ZJSZQ8GLy00toOpPjyWqIc2CIsrXd+2DEGQiZUHsxzoxblnba4FOo3XLGhLA/QB8HW9anbjhEVZU+TwjD/W2XUpQEJbxh/3IuAFKaGeosZqGHOTC7mx9nqrKJaRiDegBXSww6/0hNLGEyskP2vXJ+HjLO8EI84dV+zJxNyHUDWNDyjT8/Tk6cialVUOT/H7cGXLhFPbuzcH4lpeVsQQczpNtg0K0RqXB9NOn67sUKXP,iv:suHVN3x9MDjv3Ln6Erxh4H/4hHRBkLBlyUzEz87jc6A=,tag:oo+JkI/DP2LFvddPrLj+VQ==,type:str]
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWGRlK1kzdGd2dUU0V3ND
        QVNnallNZ3R3Vi91ZkJ4ZnhTMkZyYkswM0hjCmlMRTJQeS9UeWFkbmJVaDEyV0ox
        U3dsRUcvR3MzL0JQME5zY1lMNGpGaTAKLS0tIDBjZ0NFOThSaVpFeHJuUkIrREdZ
        OURNWEU5L2tiTzNIa2srWHdWWEZyOFUKRpHe99Ouxeua1BnZHhGNmxf30rGe+aIH
        f5a++f3+xACR2wjUWONBeB5Cw+W4L6SHnYfQQH4pNyXBq7syqg5lbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:56:12Z"
  mac: ENC[AES256_GCM,data:2nZEoQVBkMH/beKvePDieYHC8ZCoXAojRk2u3SLkjdz2sbpjbJh3s1Ezx7BDD6yGMhtRsJ0KAcsuiXMx3Cd5uRZH4PeJJnIIN3hwHubpRa+bXC3KzTTxUCkmLlJaxePEE9ew0cJPUTCGB7tmYc544aLX68Vzbjvu9XA8XiWxYgI=,iv:xciHfGjsUCJLGe2ZsvEvrUyDzJc6PGHCLGqWo6qNiwo=,tag:FHeI5SyVWqcMRGFS9Adpmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
