apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:lrEbXqE+HOTvrKq7VFjK5MDK41LEkOxjrcgvC8sIUUQ=,iv:8pLJKpSkxim9CPuTTblcOuYKmeVUAcqMHcKQNc4guOY=,tag:pN/itBDbqRofukVLWCfp+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHJvVVNxckFxbXQyRmhM
        UlFRWEFWdVIxSVRrU3E4Q211cGtmcEgyNzBZCnAzT25wL2Y4WkFpcG9PMndIYzg3
        Z0FPTE56SCtCT3B0Wm1uMkplaHpWVEUKLS0tIFBrZHJiblFvMXhoTjlOZWFHKzE2
        L0c5YWZuaE16aXhiZDdSbTJtU08zNVUKIu8Y8oifbaYT5daQ0Qt1LJ6n/eHKw1sl
        8+7DPlQZczQf/MDEJnLqMkAiy0WaP2gfxT/OyFZk47nTyKIIqk7YJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T21:29:15Z"
  mac: ENC[AES256_GCM,data:osH+u3Q8cf3xnWkJ//akni2UB1p/L0QCUk08yWXavuW5WLgRNZIBkoUl+wWeQRNeQnUy7mONFaBlqJ8vTF9H/3KkRufvThzC5/aixWhcesTuQA7+/m8HVco6VzSbmnKqWcfXuH1Hhb6BRXKLAvW1IFAPgSCJZVFvQFcwI7Co83M=,iv:Wil/aZV3az0gwlaZwRjJXqAJ3cK0VGlUGHAZu9Zsz1A=,tag:14QZePKHkHcL2f+QqtMkFA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
