apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_API_KEY: ENC[AES256_GCM,data:iMMlNPfFqausVeob3oJxmlht1ALX439rYV/UExRdNuQ=,iv:M/k8uW2vVsFT5CsDC648L+zN7Ku0FRH0z5KOI2bOvAU=,tag:6bKTORByxHPYBcpbcMqPsA==,type:str]
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHJvVVNxckFxbXQyRmhM
        UlFRWEFWdVIxSVRrU3E4Q211cGtmcEgyNzBZCnAzT25wL2Y4WkFpcG9PMndIYzg3
        Z0FPTE56SCtCT3B0Wm1uMkplaHpWVEUKLS0tIFBrZHJiblFvMXhoTjlOZWFHKzE2
        L0c5YWZuaE16aXhiZDdSbTJtU08zNVUKIu8Y8oifbaYT5daQ0Qt1LJ6n/eHKw1sl
        8+7DPlQZczQf/MDEJnLqMkAiy0WaP2gfxT/OyFZk47nTyKIIqk7YJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T18:50:30Z"
  mac: ENC[AES256_GCM,data:/KsDWS/MqcL20C5CQI+wvOL95aO638wVT7W361D9fmXqsfGqUorE3rAb51wDXDLL/55RPHY+puhe+7WKSfGFSxY0eRAkXVtCNvV+oGjnIqklk11mrRlU9MAJ1QlAtbOy23bih+/6Q6jCSsJCr0zOiOf/IS3byxD7T7xYtrr/7NQ=,iv:VpsRk8+htomk+7SXw1J34Klr0o9NSKD9Hs3CrI/e/ys=,tag:mFWSlv/MH6RGeG0TD4asgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
