apiVersion: v1
data:
    UNIFI_API_KEY: ENC[AES256_GCM,data:/xqP4B6CL2pTm7V0TihEKCebK2z9gn0O9NhDIlirp1k=,iv:8YLIt9AaUx1EfcTUOS1xhAHQZwuJu0bai/oU8ZXbga4=,tag:j1xD0bwwMkSmWID8ADjFng==,type:str]
kind: Secret
metadata:
    name: unifi-dns-secret
sops:
    age:
        - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQVBRMTNVQUJXYmdEczRP
            YlJQd1BvTnp3R2lrVFF3N2JsT21NUUF4bUJBCkVKdnJNbklwRGxxQ2Y0SHBFWUVS
            LzhBWDIybDNoZllMdTY0SVAzY0U4YkUKLS0tIG1MODkvV3Boamw3d2lJTkVKRTVV
            aG9NWEFtcTVkVS90NkVjUjRKNU9WancKu+Ym8bMSuFyEvIBz693eatW8Lw6F4kfX
            uKEL84X2HeD586RzvNR/BjMvZD5pqyTe9kbcU4D0CiD/nPwDtRSW2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T21:46:42Z"
    mac: ENC[AES256_GCM,data:zoYIZRxMrNTuFFKhESD7I2odE+dQbZnrVJX6HSs7saZgP7Po85xgp0XNtew1fOIkupyp4TUahhBaYgFvfCh4EclOMOzuI/FWlpkEieqe8oeDmsX6ulkPcUUMhk5IovSiUyKED3Gpwjvo2Px9apCcxxT6MIww/TEY6Gpxe8NVWBk=,iv:H5sgE0oYgj9oh3mDkzjoC0rIZ/TzqPVjHOvdBtY6Sis=,tag:iZeltntk1T5/gNEP9a8qYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.1
