apiVersion: v1
kind: Secret
metadata:
  name: coder-external-auth
stringData:
  #ENC[AES256_GCM,data:DfXeU/sHALBIFG47U3Cb9Nz78tUTfvECes821/ZgfN5vr6IGvOUJcNeHtH36/hGfCJFC+J0PDvl/zs4lqadaILFh0t4opg==,iv:+r/E0h/AxouBAoXWvRsOKP8WHbs9vJcWo5UO6XwqjGs=,tag:3jpYvE24/SLyQkI0eqGOlg==,type:comment]
  #ENC[AES256_GCM,data:Vkkd/F0CJSRF3Di/JOi64MRagHB0qwL2NR8J3GDOJT1qh8IgK7KVef0CTVIWJF4RWXNj6h8ppFKPp98ag3WyK05+6pU=,iv:EYBp+zeDkTI5JfpaZArp9N4D9HrjLVrCQ2sbs7T2Q9o=,tag:7qO9fq4N4/wO4E1knf4FUw==,type:comment]
  #ENC[AES256_GCM,data:b7ZYEFw53L1qGrkJfNYyy7hwlwNwsxoDT9hpBH8Vrc8V4mE=,iv:pV6tRQ+RKgn+2WLkAvS7cBn/7+NYO5oz3eWQZNJDBv8=,tag:uEN+Kfk79/5/lgK71Cy/Jw==,type:comment]
  CODER_GITHUB_EXTERNAL_AUTH_ID: ENC[AES256_GCM,data:fJK1oumK,iv:WK9Vfn5d6SqXCQZV0I5udgBsqZs0MRs4jr0W6q4MlM4=,tag:8WDQ42lMRi09MfeqXr6IhA==,type:str]
  CODER_GITHUB_EXTERNAL_AUTH_TYPE: ENC[AES256_GCM,data:iLX5U43M,iv:aJ3BzZKWT/Z1BYyb6GQ6DeMB3SHey5pWmEoTRxyGxOQ=,tag:JiKg1Rt2c7P40ZHNYscsFA==,type:str]
  CODER_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:ipf5/qb2D78=,iv:y9pwyFhpSxGJDWQvIrdKhOgatsp6LSeW+jy0PyjY364=,tag:tkZAdCQxYQhqp1iPfT6IsQ==,type:str]
  CODER_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:EPro7B3XlYc=,iv:wqKbY1b7H+beidKh2IvgRQjLH8JWao/jRVxUd9WqSbg=,tag:sK2mhcQX07Z31YaPUBTcSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTlhTUTluS05nZm02dnF0
        VXp3TUlwbkZzNlVWdDlJWTN1TkR3alJsSDNNClBzdG1yaWR6U2l4WkV1TXU1UWtk
        M1ZIOW9aUXI4VkVEQnpyWmdkYTFkcU0KLS0tIGlsSUJXYVlKRTF4Y2RrejN4M0Fy
        SDczR2htTi9xT3FMV2lWd2gxdHJTNUkK5obCIDWUMcBtrs1hc6DAgRGRo+u4WfQY
        Ul8XPw/IdvdDDGKdlV3G920f9jMc8kJsyYyHjzMdMutanBNPqfimlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T16:55:20Z"
  mac: ENC[AES256_GCM,data:BG1D+4VUJlHjrWo/xe3hPf3gGjSBPkQ7W51Q+h6VK36grzF3YJDHxYvlf2J4Ip3jyyOvCT3fXBQkpDrKpNUu+tt8gHAorUVpOKmMz9G4EjM1vITLoXNzGX4agI7N3GMpGSp5ZV9zE6XBylm9YRVltcDuLs1khS0iVLi/Q3Pxsxo=,iv:WFRxZDYn5V0PaqNMgVKAW+kUu4btpSHq4hLrrNGCuYM=,tag:5o4c6oxFkVwFXbYxq4i96w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
