apiVersion: v1
kind: Secret
metadata:
  name: coder-external-auth
stringData:
  #ENC[AES256_GCM,data:S8Ek7iXUtoWygNOiLfxhFyEGnLpC2u9psIZKFGtLbN9Ohw56F2tE9Kf0A1zrFay48E7Js/C2w1+lUh6UezorE8HNZMg=,iv:dX/DvN1fsQjTudDGVJWZ58fbqaDWwBhtzR/XPixgWXA=,tag:dlUgSilr4Y4vd/bNyCUgtw==,type:comment]
  #ENC[AES256_GCM,data:Jze5OBXOcZ56lIuszfI8dANjqYJEEMGHakZ7NwPsbhb08FsJgUXV5uP87KUe8HP3mP9eoDDVL/RLRuIQDhhQXOfRVtqNKVJAfvDe9go=,iv:PT2poC5ImCTTXqlS7cfzzuA5/BljDKhn6Pe8Q57IuV8=,tag:kSHvWhyda61ZCLGCDpfM/A==,type:comment]
  #ENC[AES256_GCM,data:mffil1Xog1xRZZAeGizlrR9m+yWzRmqONK+h1pD+6Ufldx1hTccphITXdVs1Tt2BIG9kmaZrvewZ9o/AKZ11kBf+YE0/SGDS6ghelcDQeA==,iv:gRFNU4N9UlFH2NSeFMUdwesjPN1AjIHTwOA0o0AJssU=,tag:cL7O7ilU3SMBs9dfQDhLKg==,type:comment]
  #ENC[AES256_GCM,data:OZDgXzkFYpzHmCQdqtIguhhtBsH5xBKHBmK3N8TZj+ya4sNHXNPpZlXdkeqsmXlMCigpUwTlZTHgVHRA1Nl3yewxY9fRlw==,iv:yA7+jtl4lfGuY7cUzrPRMjTaXfQ0lNDJGQMV4WoM6ZE=,tag:HOrvG6VxyzDhn2HkdC3kKQ==,type:comment]
  #ENC[AES256_GCM,data:/d0RmIz7C6WZVWIZs9ulNpQ8OLgeog80+39Qc/e+AtXcJtJwQzONH/3iJuG3oxglz2bFCUmFztc=,iv:tgPBgRb2Gk4Oxwl320aPw7DX+f6l9Tj1rNc/eMNg1vg=,tag:Ml9z+x/bSVvSSnjqAn+uDQ==,type:comment]
  CODER_GITHUB_EXTERNAL_AUTH_ID: ENC[AES256_GCM,data:RzETon8a,iv:wKqIyCBoj4iM1490hH0OgmKZa2OXwZnv+0JRJlqcyFI=,tag:DdzFgd0bOGuBniyVtUp1AA==,type:str]
  CODER_GITHUB_EXTERNAL_AUTH_TYPE: ENC[AES256_GCM,data:33Kbq3vs,iv:0e5AUNRtSrAFUsjxRWltISnnt+Lz6M75MSWu9e+nka4=,tag:tOyAs2IAxc/Akk2NrWn8/g==,type:str]
  CODER_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:DGaEemZa3MI=,iv:rewcyvwW1EOjsiFmpPPoGLmw0BwNQVaCdQs0Ix73mxE=,tag:tTkPGKx7od3YQIepJLt3Gw==,type:str]
  CODER_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:qEPOwhXbGL8=,iv:9qsmB5SV+uJr8cBLN95hnIJyBOr756IYJSRY1Vdnlww=,tag:M5/Ia5JCMwLpeXmMpCyVSw==,type:str]
  CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:VBeD5pacrEc=,iv:ZAd9Jotp0UKmjAaAPU6Ny1t2mB5zWUfY5MVXm9MtjU4=,tag:EjTzY5HNo72GBd75W1QoZQ==,type:str]
  CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:td0n3yo8mRg=,iv:p46Iol81RB220P/E9StvBE1eb//k9ix+HUEgraf3+/s=,tag:116x0MSnoO6gHu5SMMxCLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVlZob094QmM0SlByOEhS
        Uy8yUHdrMWxqQko5YiszUXdTRU1RL2JFU3h3CmRaOGFvS1E3emovcGRCc2lDSmY0
        Y2djb1RybGlUQ2EycHFGYmhvd3FYaEUKLS0tIGEyUVFYbm5WRWo5TGFHVkdmb2hv
        RlhCSEQzK0NDOEZYWlZIeVp1WS9ISjgKOnngD79rrK2ShIadeWMppO/lcyptJ+ED
        D0bs81y49Q8bcphNvmDnhXP1sevi0opUDkN+l6dFV1XkOVRt7wVzqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T18:57:16Z"
  mac: ENC[AES256_GCM,data:AfpQXxhXXbcz8Hwdh/jJFvdlgxzID0Oz5eRriTxVqDtxdL1VxbhEMfdeuPJAZuUvKdFPwVLjOmta2aiv53Ntlt1DoT9LBxSEA1zs4G1iqwLNld5pBh9Cca7bZe1cAua9CpKnEJ57aPr6oVqkD4o0+kcrbdHaIeD/S8ge4ZIm+2s=,iv:ztCRavc8xpxDkQ7UFstW8QYXAM1N/OfcOTd3QKTY3Po=,tag:JsHblVnFtodgAo/qKLkyHg==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
