apiVersion: v1
kind: Secret
metadata:
  name: coder-external-auth
stringData:
  #ENC[AES256_GCM,data:S8Ek7iXUtoWygNOiLfxhFyEGnLpC2u9psIZKFGtLbN9Ohw56F2tE9Kf0A1zrFay48E7Js/C2w1+lUh6UezorE8HNZMg=,iv:dX/DvN1fsQjTudDGVJWZ58fbqaDWwBhtzR/XPixgWXA=,tag:dlUgSilr4Y4vd/bNyCUgtw==,type:comment]
  #ENC[AES256_GCM,data:Jze5OBXOcZ56lIuszfI8dANjqYJEEMGHakZ7NwPsbhb08FsJgUXV5uP87KUe8HP3mP9eoDDVL/RLRuIQDhhQXOfRVtqNKVJAfvDe9go=,iv:PT2poC5ImCTTXqlS7cfzzuA5/BljDKhn6Pe8Q57IuV8=,tag:kSHvWhyda61ZCLGCDpfM/A==,type:comment]
  #ENC[AES256_GCM,data:mffil1Xog1xRZZAeGizlrR9m+yWzRmqONK+h1pD+6Ufldx1hTccphITXdVs1Tt2BIG9kmaZrvewZ9o/AKZ11kBf+YE0/SGDS6ghelcDQeA==,iv:gRFNU4N9UlFH2NSeFMUdwesjPN1AjIHTwOA0o0AJssU=,tag:cL7O7ilU3SMBs9dfQDhLKg==,type:comment]
  #ENC[AES256_GCM,data:OZDgXzkFYpzHmCQdqtIguhhtBsH5xBKHBmK3N8TZj+ya4sNHXNPpZlXdkeqsmXlMCigpUwTlZTHgVHRA1Nl3yewxY9fRlw==,iv:yA7+jtl4lfGuY7cUzrPRMjTaXfQ0lNDJGQMV4WoM6ZE=,tag:HOrvG6VxyzDhn2HkdC3kKQ==,type:comment]
  #ENC[AES256_GCM,data:/d0RmIz7C6WZVWIZs9ulNpQ8OLgeog80+39Qc/e+AtXcJtJwQzONH/3iJuG3oxglz2bFCUmFztc=,iv:tgPBgRb2Gk4Oxwl320aPw7DX+f6l9Tj1rNc/eMNg1vg=,tag:Ml9z+x/bSVvSSnjqAn+uDQ==,type:comment]
  CODER_GITHUB_EXTERNAL_AUTH_ID: ENC[AES256_GCM,data:RzETon8a,iv:wKqIyCBoj4iM1490hH0OgmKZa2OXwZnv+0JRJlqcyFI=,tag:DdzFgd0bOGuBniyVtUp1AA==,type:str]
  CODER_GITHUB_EXTERNAL_AUTH_TYPE: ENC[AES256_GCM,data:33Kbq3vs,iv:0e5AUNRtSrAFUsjxRWltISnnt+Lz6M75MSWu9e+nka4=,tag:tOyAs2IAxc/Akk2NrWn8/g==,type:str]
  CODER_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:WCO/HyA1q/7tyvOrsD2vTJW0JSk=,iv:xEawUneuPQyMkZ1PtJLlo4dQKo2UfjCDrjRbZiWGndg=,tag:u4nNIqLRPqi5PXg3CuBD1g==,type:str]
  CODER_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:hPQ1KW9dbDSFmCVgmkT8PxNnUFb4r4uKTYhk/z4SjdRfB2lbro1hIw==,iv:mxu+aOCio3tX6p/am2l7WLg8y/P9OZrdP8ac5xTXYV4=,tag:+PlyWUv8mdn+1IOGwLZsVQ==,type:str]
  CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:48zmvNci4VDdL83j4HorIrsRyc0=,iv:9hzu/9kcX+Tu2gnT5gDYuevStauaUPG5Gho4iT41Vs4=,tag:eImeAFonawBGxETLU+DE8w==,type:str]
  CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:wugJNpEFpSi3gP6N1ecM2p1gkgjYHbeo0018yZTC1cF0U/+fLOY3nA==,iv:J4FMxVrK7Q80qwdPklGAIecxHmox8Kqs999x6b8e3yg=,tag:GVt3pydYbqkeieXUsII/lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVlZob094QmM0SlByOEhS
        Uy8yUHdrMWxqQko5YiszUXdTRU1RL2JFU3h3CmRaOGFvS1E3emovcGRCc2lDSmY0
        Y2djb1RybGlUQ2EycHFGYmhvd3FYaEUKLS0tIGEyUVFYbm5WRWo5TGFHVkdmb2hv
        RlhCSEQzK0NDOEZYWlZIeVp1WS9ISjgKOnngD79rrK2ShIadeWMppO/lcyptJ+ED
        D0bs81y49Q8bcphNvmDnhXP1sevi0opUDkN+l6dFV1XkOVRt7wVzqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-24T19:17:34Z"
  mac: ENC[AES256_GCM,data:fNWn0r6M2Hz6nC1mxeomqfDBp23jJIpan9QNObjTHxg+YyGNLpXH7mMY6VRlxrF7Bs/8HC8C2R9REpMSpkI6En7HBu792ubT+s0I/svbNfUOrtAZ7Q5sZ+gRzKTBMELOl/0VRz4wYIW1GVi2DLWxYsdhxfGJBj9NUReX1T6O51A=,iv:YkACmDOi4I+KD/vT11yNbZDYMGZbM8K1KR3iCjv+QjQ=,tag:IG6kre/+bgKd2aZwVB7stQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
