apiVersion: v1
data:
  LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:gf1SB/kfVyAGLg4oTpmY+EBGYw1oWNq1pipp7I8Jj4Ge5EdadO6YrcZgD5MrOCwxBKEr9lntN30FveFc8o14HA==,iv:atNI2qFCEpGw5a4eN3Vmyqykphn+rgQ6W2itpJV3mLo=,tag:NZbJ0lKiEwW2/6kEXKS0YA==,type:str]
kind: Secret
metadata:
  name: lidarr-secret
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSlR0bHI3a3lQdDRHdndT
        RTBadXFNT2VGa0xYY1ZPK21SbFYzNElwZHd3ClphRjlRUVVNcDRBQjhUdDRpMUdJ
        SmhzZEpIdXVYbnJxVDY4aXp3SG1GSWcKLS0tIEs0SUxHUThML3RxYXFKK1F1My9H
        OElNUng4Si84VzRSTE93dVJCcmV3T2cKR8kv4i2R1SOd4JPKMEret4gtK/Ir9wmU
        frc+gXgmzO+vZhtTmltzbCoKf/lUoPkwQCXfNXY8XiiUlRleLj5IwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T19:58:08Z"
  mac: ENC[AES256_GCM,data:3qODtWRelQ0b5WehkytISbD014g8F+zOPBAiGZ41GpM+dKLTGx6ooDJqCkX2RtwDCrkPQfEfAP0de2KyZ4DHEHdYx78Z3yL+ZJT9eX0zjnkpzI6FrJ1Jp9/XN9M2jfSNPBLjMVlJdnBOHsAuqIV7XZOnTjSrarhxPMNvNJrEUvk=,iv:VADGgJ0nMPXzWwmAr4o2DWNmH/2BierafR9MZ+NDTv8=,tag:UYzZb3Ppq6SgoShOLjkhTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
