apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Frac4sJBwfwNu7Lhat0rolYSbTHRX97kRuUWMbZlJrMqxZo45pUNMoODINYjf1JOLUnGZXI=,iv:kkEZnqEPS79FapxLv3PAFoU2a0naBmwskmqW9uitL3M=,tag:VLdgphKC5F56UkaxFOeISA==,type:str]
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWFh6MU9hQVFuUUQxSHJ3
        RTIyQnJ4Q1VxbWdMYmdkazdzS0VrY1F1NmdrCmxPYTBrOEpkaTE2MWJsVy9wdW9O
        eW5qbWUrVkRqbEExUHkzZEVDVk9QTkUKLS0tIFVJaUhSODRTNCsrSUNNY3JZeStZ
        dng2dVZwYlJnSW96Qi9MU3dIcTMrQVEKy1Xv1eL8Xfxg5jPccsOMmPH9J5q9ExfJ
        aG9w4bFVoW66T2AkaM6xg9RUeE6aRJEJQPDlnOg4r9qre1nywNlBjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:56:12Z"
  mac: ENC[AES256_GCM,data:iXpE8DqncddcQ+SfdNz5/1HtzNfnZpJb6QOWcLHY1uwJLAGCR+yvwQ5Pya7+evKA7wov83G3B8gBpZ7wGtCdoB9PP+dA2KdnYYjvQ8soD6CWHGA+bf0tBosbyPTKprLh7OEC7h31IXvJWSHZdDKIp0fA2HF53ZTAth7O4S8t0XQ=,iv:sF0gGWKeDjYqxu5g2L9kaPmcIePNkV2lw5u41Ud/l14=,tag:kvVB8QcNBt4rpaveEUp3MQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
