apiVersion: v1
data:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:522Gtk+QIyqmSAKh/8DHwOkHnfUTHPENs7/6N81M3NSfs32mDkYQdqkiTE88EWKM5TuOT0SHILjak6Ifh1SSVA==,iv:6cYhMlZQ8VR9PxHRl+Z4r/REaOg8I5a1haXRtqIB2F8=,tag:puNfVkQpy84IaHRc2EGEeQ==,type:str]
kind: Secret
metadata:
  name: radarr-secret
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUjdYa0NyUkJMTUtSUjF3
        Um9qanlBZzlFLzRzOG9ZdWU0UnhFM3luS1V3CjQwZk50TFVCUm5MQklsdjFkaFky
        dWJpL3R3ODdLZ09LUi9jQVR3RWtXOGMKLS0tIHEzRkxMb2I4NkJaTys2VGRmYld0
        dUtCWWMrVnVtWVdvcEtBdHl1cU1OSlkKpeBpur1TlYfMUhCnpjjvnQKvpB9Cbypp
        XGiHl48bzN4MXeXAl0CmYpqKNXnM4bl3nhh5m4lR97Ylp4Edm3yqcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T19:58:08Z"
  mac: ENC[AES256_GCM,data:Lq22GN6zeH6egCSHNZQmcjxE2G7qeNT26GB2NRREAQ0Mw+qac5NiVW+lrMaYaZ87Ruw7L2wxi7zuPQY3dX3kq2iZj1Cuf0DFicmeKpseXQ9mYZhh24h4goFmO744L/Df28HLCyl39VzXxYMN+5lXJCb1l1t/mLLz0isu683Rq4I=,iv:LkFMhc6xWbGvJoXpcyWg8zCOYpvP1i+OLRLfpl+QTNI=,tag:n4Rla8bGiYZ3tRE1HfNOXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
