apiVersion: v1
data:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:Y/Tj/tR9e7u9+N9DZ2sm26WuskW4Etxpy1dJnno6nisq/SVo8/4ZbwYTodKE1yr8VW8XxNjiCiLy9fSyP1vxkg==,iv:U+73sihNsxBAXUCKJpWQqWNPb3Q5QdSxPPaLx0E/wBc=,tag:xVpMGRS8+Hvo3mDZFS3vQQ==,type:str]
kind: Secret
metadata:
  name: sonarr-secret
sops:
  age:
    - recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYkFHM1QzNVB2MW1pM1FB
        RDVQd1psOG11U3hhVnJGWXBubmhzQ0YxN0hRCjFES2x4Qy9ZVzF3WnpkdTRjbmV4
        eDdvSWJ4azVIblpaRFlocDBQUmlDb2sKLS0tIElmNzRWYlBxWkovdVFiTDJPaTJS
        M0lDVTB2L1lnUE1BV1JWVS83L2lja00KopJZK7POH0v+NMGVcYRvUX9c4AZPhBVm
        2rWsV3gIS4piWOvn8HIObNxwzphvbmeBdIZyUE50bDGwJ335YxKXIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T19:58:08Z"
  mac: ENC[AES256_GCM,data:Czx3wQ6IyR7mAKMQyx8TAsN9bLZ2N4yMepLvu/w4o3Xsup7B3n+qh6JxTT3sYqEJY/t1hgDvN1ESLX0o/MtHAbNFXiDoiuyWwiQR6qg6WWxXLC4GSUpQdcSHpAWlsnF28LAeTMYNJkMa0nAiM+iksj058CQLzphUcysF2Qc2OFA=,iv:iR37ApeB14H5jBM8vCrwDyyE1zawLsEYlQUwaw8C+Hs=,tag:R2tK+CXZv/YYfHA9s9jmmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
