apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:w1TMebMz9CVSXVFxXFS3+l0=,iv:eykHHdtEAqp7aSJw9GICCFIFGTnh6Ruhv+LvJkMi33w=,tag:HytjWNEW7NjfbPeWwXVbIA==,type:str]
  client_secret: ENC[AES256_GCM,data:S7vlfPljcmw3XULuUGfPUDWz86WA1Klgt4M67WuRjhWjdd4xbM3jl14C87p0Ff+yh0g3UF0lGw/oiIUetM3LUg==,iv:fLZ/6nBkKhOmgI/wZePq00VwLf8EokkLIc4kFPAor5Y=,tag:qIDHfk+6l0UZpJinXfZb6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5blNPaXlpU1MyclpJVkky
        L3ZKNUNXbkJ5RWNySTV2NlBtTUJvOFd4aWtzCmw4RStFR0NIMnN4SHROWVNuMnVX
        UGZVZ3paVTZlMFhZejhaWkVnMngwU00KLS0tIFFzZ3JjZ3dSRnhFZlpMTVFBMXlW
        b2JhWW9udFNNRkljQU4yQ1NKWVBvbEUKvh+dLB8182QarV0J7dPvkoaUQM1FPgc7
        bPskN9Ove1m7Fi8DAGZJc0riqZFf1Fial1I/S/WV7xHkPfEcupF48w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T17:21:37Z"
  mac: ENC[AES256_GCM,data:5GcBrtri2TwBB5eafMKH1wMMZ5Vg38BaHtX6C+HTYXP1S62e8NgKdPG6vGgk1k3sQMHy2P4chjR1XmE1tZLzXS4MA271xjNAH9ceJ2/0FR8ClQDluvyYhOGJ5MYXJOyfASBowbeKMawpJ5aCxYx+SAwJ5Sdvto0gds7f21QHEHk=,iv:JgOzAGlRx4kQrMjSTQeW4LkU8LONQwo0WQdC0tid9Us=,tag:29qm6vQBT9Ce25m9cJOgkQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
