apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:Qq349IwxCueMHA==,iv:GfFoK1NG4QX/0zkyLgU1VG1skgRLnuh158+sxJRsG3A=,tag:jGgM01QrGPbFjDyssT07Vw==,type:str]
  client_secret: ENC[AES256_GCM,data:BNs5Axkny0DrxQ==,iv:96WztlPGsqFbq/87H/OJyQUcK1wzn94/uyBC7ZuzXgE=,tag:2sr+gbBfHk8WdsjC24Vb4A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5blNPaXlpU1MyclpJVkky
        L3ZKNUNXbkJ5RWNySTV2NlBtTUJvOFd4aWtzCmw4RStFR0NIMnN4SHROWVNuMnVX
        UGZVZ3paVTZlMFhZejhaWkVnMngwU00KLS0tIFFzZ3JjZ3dSRnhFZlpMTVFBMXlW
        b2JhWW9udFNNRkljQU4yQ1NKWVBvbEUKvh+dLB8182QarV0J7dPvkoaUQM1FPgc7
        bPskN9Ove1m7Fi8DAGZJc0riqZFf1Fial1I/S/WV7xHkPfEcupF48w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1p6s652l0dn5k5ekcq56f372zq5wmvw0sv29zrw3hvck8jd8p74kqdcp86z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T15:58:34Z"
  mac: ENC[AES256_GCM,data:3Fmr3yMn4vGvdqX6vxiJxhfHpyOoVtQtTPVlrVgt2iW6IQnV03Tx3az5un0AiTGLoxKYmzkzz7pek5kxAzkDeYGH1l1lIn51gdvrmKQTfRCAynLney3lBapBI8Fh4d3XM1L0hMuZiiFy4roSLNVi0QhiGg94g66h/qAIDHHeop8=,iv:G7rluM7oG4N6r41gAKqgevjalrzB4NerOHOgPeb5h7Y=,tag:7w1AiDTpIX1/H+ZtSdt+VQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
