---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chartRef:
    kind: OCIRepository
    name: homepage
  interval: 1h
  values:
    fullnameOverride: homepage
    configMaps:
      kubernetes:
        enabled: true
        data:
          kubernetes.yaml: |
            mode: cluster
            ingress: true
            gateway: true
      widgets:
        enabled: true
        data:
          widgets.yaml: |
            - kubernetes:
                cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: Cluster
                nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
    controllers:
      homepage:
        serviceAccount:
          name: homepage
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.12.3
            env:
              HOMEPAGE_ALLOWED_HOSTS: "homepage.${SECRET_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 10
                  periodSeconds: 10
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: nfs
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /app/config
      kubernetes-config:
        enabled: true
        type: configMap
        identifier: kubernetes
        advancedMounts:
          homepage:
            app:
              - path: /app/config/kubernetes.yaml
                subPath: kubernetes.yaml
                readOnly: true
      widgets-config:
        enabled: true
        type: configMap
        identifier: widgets
        advancedMounts:
          homepage:
            app:
              - path: /app/config/widgets.yaml
                subPath: widgets.yaml
                readOnly: true
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Homepage
          gethomepage.dev/description: Application dashboard
          gethomepage.dev/group: Cluster
          gethomepage.dev/icon: homepage.png
          gethomepage.dev/href: "https://homepage.${SECRET_DOMAIN}"
        hostnames: ["homepage.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
